title: Days until Late Night in the Phog
description: >-
  Countdown the days until KU Jayhawk Basketball's Late Night in the Phog.
baseurl: ""
url: "https://daysuntillatenight.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - "*.py"
  - build
  - CNAME
  - dist/
  - Gemfile*
  - justfile
  - modd.conf
  - node_modules
  - package.json
  - Procfile
  - README.md
  - requirements.*
  - src/
  - tailwind.config.js
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:  # process the _data folder
  components:
    output: false
  latenights:
    output: true
    permalink: /:name/
    layout: player-list
  players:
    output: false
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "latenights"
    values:
      layout: "latenights"
